name: Renovate

on:
  schedule:
    # Run every Saturday at 00:00 UTC
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug' 